<a href="https://colab.research.google.com/github/Samar2411/Python_Paper_Airplanes/blob/main/Week_4_Kevin_Tang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lession 4

**Numpy and Pandas Part 1**

Lesson Goals:
- Learn to manipulate Numpy Arrays:
  
            A. Create an Array
            B. Index an Array
            C. Operations on an Array



# Numpy and Pandas Part 1

Numpy and Pandas are some of the most critical packages in Python for Data Science. The numpy array structure is ubiquitous and if you want to do data science in the future, you will probably encounter it at some point. 

So why do we use it?

1. Everyone else is using it!
2. It supports advanced mathematics.
2. It supports many methods that make it easy to do statistics and analyze data.

As a reminder to import a library, you use the syntax import Library as alias.

To call methods from the library, you usse the alias_name.method

In [ ]:
import numpy as np

Coding time!

#Creating an Array!
The most important numpy data structure is the numpy array. It is an indexed structure containing data. 

There are multiple ways to create a numpy array but many revolve around converting a list to an array! If you already have a list declared, you can convert it with the syntax np.array.

You can also put in a list of data into the np.array().

In [ ]:
array = np.array((1,2,3,4,5))
print(array)
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5]
[1 2 3 4 5]


#2-D Array
If you put in a list of a list inside the np.array, you will get a matrix! 

This is not a mathematics class but basically a matrix is a 2-dimensional structure where the data is organized into a structure that has rows and columns.

In [ ]:
list_of_list = [[1,2,3],[4,5,6]]
matrix = np.array(list_of_list)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

# More Methods of Creating Lists 
Numpy also has many methods to create lists with preset values. We are only going to go through a few of them

To create a list from a list of numbers, use np.arange(). You can also create an incremental list by adding a third argument. 

np.linspace creates an array with a range but the third argument gives the number of evenly divided points in the range.

You can also create arrays or matrices of just zeroes and ones with np.zeroes and np.ones. If you want to create a matrix, the first argument is the rows and the second is the columns.

You can also generate random numbers by np.random.rand. The third argument is the number of random numbers. You can also add in the range as arguments and only get integers with np.random.randint

In [ ]:
array = np.arange(0,11)
print(array)
array1 = np.arange(0,10,2)
print(array1)
linspace = np.linspace(0,11,10)
print(linspace)
zeroes = np.zeros((2,3))
print(zeroes)
ones = np.ones((10,25))
print(ones)
random = np.random.rand(5)
print(random)
rand_int = np.random.randint(0,10,5)
print(rand_int)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 2 4 6 8]
[ 0.          1.22222222  2.44444444  3.66666667  4.88888889  6.11111111
  7.33333333  8.55555556  9.77777778 11.        ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]]
[0.5

#Accessing Array Attributes:

You can access information about the arrays through built in methods.
They include size, np.size, dimensions, np.ndim and shape, np.shape. 

Size refers to number of datapoints.

Dimensions refers to whether it is 1,2 or 3-D.

Shape is rows by columns.

On this note, np.reshape methods allow us to reshape an array to specified dimensions.

In [ ]:
array_ex = np.arange(1,11)
print(array_ex)
array_ex = array_ex.reshape (2,5)
print(array_ex)


print(array_ex.size)
print(array_ex.ndim)
print(array_ex.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
2
(2, 5)


#Indexing Arrays 
Like a list/dictionary, numpy arrays can be indexed to access values. 

You can obtain data in some ways like you would a list. array[0:6] accesses the first seven values. array[5:] access the fifth value onward.

You can reassign the first 5 values with array[0:5] = 26.

array[:] access all values.

You can return the reverse version of an array with the syntax: arrray[::-1] 




In [ ]:
array = np.arange(1,12)
print(array)
print(array[0:6])
print(array[5:])
print(array[:])
print(array[::-1])

[ 1  2  3  4  5  6  7  8  9 10 11]
[1 2 3 4 5 6]
[ 6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  3  2  1]


For 2-d arrays, The syntax is array[row] [column]. You can also do array[row,column]

We can also grab larger slices. The syntax to grab all of the first fifth rows and the first 2 columns is array[:5,:1].

But there is more advanced syntax available. array[:2] means the first two rows. array[:,0] means everything in column 0.

In a 2-d array, you can get a certain "block" of the array with the syntax array[0:2, 0:2] which gets an array that is the top left 2 values.

To do reverse index on the 2-d array, use array[::-1, ::-1] for reverse rows and columns.


In [ ]:
list1 = np.random.randint(0,100,20)
array = np.array(list1)
array = array.reshape(5,4)
print(array)
print(array[3][3])
print(array[3,3])
print(array[:,3])
print(array[1:3, 0:2])
print(array[:4,:1])
print(array[::-1, ::-1])

[[96 75 22 99]
 [72  8 72 56]
 [27  2 63 96]
 [95 16 29 36]
 [95 46 32 28]]
36
36
[99 56 96 36 28]
[[72  8]
 [27  2]]
[[96]
 [72]
 [27]
 [95]]
[[28 32 46 95]
 [36 29 16 95]
 [96 63  2 27]
 [56 72  8 72]
 [99 22 75 96]]


You can also use boolean logic to get out all values that meet a condition with the syntax array[array>x] for all numbers greater than x. 




In [ ]:
array = np.arange(1,100,5)
print(array)
array[array>20]

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


array([21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96])

For 2-d arrays, You can get even more specific and look for all numbers in a row greater than 5 for example. array[1][array[1]>5]. 

In [ ]:
array = np.random.randint(0,100,20)
array = array.reshape(4,5)
print(array)
array[1][array[1]>5]

[[ 6 44 97 32 22]
 [35 93 71  0 19]
 [71 81 31 18 89]
 [53 14 40 45 78]]


array([35, 93, 71, 19])

One important note!!!!

When you index off of an array, you dont actually create a copy! It is a reference to the original array. Changing the index version will change the original version!!!!

If you want to make a true copy, you need to use array.copy. This way, you can preserve an original copy!!!!!

In [ ]:
array = np.random.randint(0,20,10)
print(array)
array1 = array[0:4]
print(array1)
array1[:] = 100
print(array)

[ 2  7  9  9 13  0  1  4 12 13]
[2 7 9 9]
[100 100 100 100  13   0   1   4  12  13]


In [ ]:
#Make a copy
array = np.random.randint(0,20,10)
print(array)
array_copy = array.copy()
print(array_copy)
array_copy[:] = 100
print(array_copy)
print(array)




[19 10 19 13  8  1 12  6 17 18]
[19 10 19 13  8  1 12  6 17 18]
[100 100 100 100 100 100 100 100 100 100]
[19 10 19 13  8  1 12  6 17 18]


Basic Data Descriptions

WE can get the minimum values and maximum values of an array with array.min and array.max.

Likewise we can obtain the posiiton of the array with array.argmin and array.argmax.

In [ ]:
array = np.random.randint(0,100,10)
print(array)
print(array.min())
print(array.max())
print(array.argmin())
print(array.argmax())


[80 84 52 45 68 13 57 56 29 52]
13
84
5
1


Numpy is also set up so you can basically do math on the arrays. 

You can add arrays with array + array, array - array, array * array and array / array.

You can also perform oeprations with numbers.

More complex operations include square root or sqrt, trigonomtery, sin/cos, and logarithm, log. 



In [ ]:
array1 = array = np.random.randint(0,100,20)
array2 = array = np.random.randint(0,100,20)
print(array1)
print(array2)
print(array1+array2)


[94 86 86 80 50  9 62 90 24 71  0 96 59  1 47  5 45 65 47 51]
[ 1 90 37 87 78 81 91 60 58 33 38 46 32 92 68 79 93 96  5 72]
[ 95 176 123 167 128  90 153 150  82 104  38 142  91  93 115  84 138 161
  52 123]


In [ ]:
array1 = array = np.random.randint(0,100,20)
array2 = array = np.random.randint(0,100,20)
print(array1)
print(array2)
print(array1*array2)

[71 71 40 42 96 52 84 45 46 35 50 24 35 91 36 58 93 10  8 42]
[82 18 11 63 48 97 46 48 56  6 14 94 82 16 68 98 10 17 69  6]
[5822 1278  440 2646 4608 5044 3864 2160 2576  210  700 2256 2870 1456
 2448 5684  930  170  552  252]


In [ ]:
array1 = array = np.random.randint(0,100,20)
print(array1)
print(array1/2)

[32 12  0 35 16  7 18  2 66 76 52 23 43 56 46 96 14 91 71 42]
[16.   6.   0.  17.5  8.   3.5  9.   1.  33.  38.  26.  11.5 21.5 28.
 23.  48.   7.  45.5 35.5 21. ]


In [ ]:
array = np.random.randint(0,100,20)
print(array)
print(np.sqrt(array))

[19  7 62 21 13 11 65 69 70 39 45 98 13 23 97 21 56 40 56 97]
[4.35889894 2.64575131 7.87400787 4.58257569 3.60555128 3.31662479
 8.06225775 8.30662386 8.36660027 6.244998   6.70820393 9.89949494
 3.60555128 4.79583152 9.8488578  4.58257569 7.48331477 6.32455532
 7.48331477 9.8488578 ]
